blueprint:
  domain: automation
  name: Hue Dimmer RWL021 — Clean ZHA Version
  description: Stable Philips Hue Dimmer RWL021 handler (ZHA, cluster 6 & 8)
  input:
    zha_device:
      name: Hue RWL021 device
      selector:
        device:
          integration: zha
          model: RWL021

    Power_Press:
      name: Power — Press
      default: []
      selector: { action: {} }

    Hue_Press:
      name: Hue (Bottom) — Press
      default: []
      selector: { action: {} }

    Up_Press:
      name: Up — Press
      default: []
      selector: { action: {} }

    Down_Press:
      name: Down — Press
      default: []
      selector: { action: {} }

    Up_Hold:
      name: Up — Hold
      default: []
      selector: { action: {} }

    Down_Hold:
      name: Down — Hold
      default: []
      selector: { action: {} }

    Up_Release:
      name: Up — Release
      default: []
      selector: { action: {} }

    Down_Release:
      name: Down — Release
      default: []
      selector: { action: {} }

mode: single
max_exceeded: silent

variables:
  target_device_id: !input zha_device

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id == target_device_id }}

action:
  - variables:
      cmd: "{{ trigger.event.data.command | default('') }}"
      cluster: "{{ trigger.event.data.cluster_id | int(0) }}"
      args: "{{ trigger.event.data.args | default([]) }}"

      # Determine direction for level cluster (8)
      direction: >
        {% if args | length > 0 and args[0] is number and args[0] > 0 %}
          up
        {% else %}
          down
        {% endif %}

  - choose:

      # POWER button (cluster 6)
      - conditions:
          - condition: template
            value_template: "{{ cluster == 6 and cmd == 'on' }}"
        sequence: !input Power_Press

      # HUE button (cluster 6)
      - conditions:
          - condition: template
            value_template: "{{ cluster == 6 and cmd == 'off' }}"
        sequence: !input Hue_Press

      # UP/DOWN HOLD (cluster 8 move)
      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'move' and direction == 'up' }}"
        sequence: !input Up_Hold

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'move' and direction == 'down' }}"
        sequence: !input Down_Hold

      # UP/DOWN RELEASE (cluster 8 stop)
      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd in ['stop', 'stop_with_on_off'] and direction == 'up' }}"
        sequence: !input Up_Release

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd in ['stop', 'stop_with_on_off'] and direction == 'down' }}"
        sequence: !input Down_Release

      # Optional: treat quick step as press
      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'step' and direction == 'up' }}"
        sequence: !input Up_Press

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'step' and direction == 'down' }}"
        sequence: !input Down_Press
