blueprint:
  domain: automation
  name: Hue RWL021 — 6 Click Stable
  description: Supports up to 6 clicks + hold/release for RWL021 (ZHA raw mode)

  input:
    zha_device:
      name: Hue Dimmer Device
      selector:
        device:
          integration: zha
          model: RWL021

    click_window:
      name: Multi-click window (ms)
      default: 450
      selector:
        number:
          min: 200
          max: 1000
          unit_of_measurement: ms

    Power_1: { name: Power 1 click, default: [], selector: { action: {} } }
    Power_2: { name: Power 2 clicks, default: [], selector: { action: {} } }
    Power_3: { name: Power 3 clicks, default: [], selector: { action: {} } }
    Power_4: { name: Power 4 clicks, default: [], selector: { action: {} } }
    Power_5: { name: Power 5 clicks, default: [], selector: { action: {} } }
    Power_6: { name: Power 6 clicks, default: [], selector: { action: {} } }

mode: restart
max_exceeded: silent

variables:
  target_device: !input zha_device
  window: !input click_window

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id == target_device }}

action:

  - variables:
      cmd: "{{ trigger.event.data.command }}"
      cluster: "{{ trigger.event.data.cluster_id | int }}"

  - if:
      - condition: template
        value_template: "{{ cluster == 6 and cmd == 'on' }}"
    then:

      - variables:
          clicks: 1

      - repeat:
          count: 5
          sequence:
            - wait_for_trigger:
                - platform: event
                  event_type: zha_event
              timeout:
                milliseconds: !input click_window
              continue_on_timeout: true

            - if:
                - condition: template
                  value_template: >
                    {{ wait.trigger is not none
                       and wait.trigger.event.data.device_id == target_device
                       and wait.trigger.event.data.cluster_id == 6
                       and wait.trigger.event.data.command == 'on' }}
              then:
                - variables:
                    clicks: "{{ clicks + 1 }}"
              else:
                - stop: "Done counting"

      - choose:
          - conditions: [{ condition: template, value_template: "{{ clicks == 1 }}" }]
            sequence: !input Power_1
          - conditions: [{ condition: template, value_template: "{{ clicks == 2 }}" }]
            sequence: !input Power_2
          - conditions: [{ condition: template, value_template: "{{ clicks == 3 }}" }]
            sequence: !input Power_3
          - conditions: [{ condition: template, value_template: "{{ clicks == 4 }}" }]
            sequence: !input Power_4
          - conditions: [{ condition: template, value_template: "{{ clicks == 5 }}" }]
            sequence: !input Power_5
          - conditions: [{ condition: template, value_template: "{{ clicks >= 6 }}" }]
            sequence: !input Power_6
