blueprint:
  domain: automation
  name: Hue RWL021 — 6 Click Stable
  description: Supports up to 6 clicks + hold/release for RWL021 (ZHA raw mode)

  input:
    zha_device:
      name: Hue Dimmer Device
      selector:
        device:
          integration: zha
          model: RWL021

    click_window:
      name: Multi-click window (ms)
      default: 450
      selector:
        number:
          min: 200
          max: 1000
          unit_of_measurement: ms

    Power_1: { name: Power 1 click, default: [], selector: { action: {} } }
    Power_2: { name: Power 2 clicks, default: [], selector: { action: {} } }
    Power_3: { name: Power 3 clicks, default: [], selector: { action: {} } }
    Power_4: { name: Power 4 clicks, default: [], selector: { action: {} } }
    Power_5: { name: Power 5 clicks, default: [], selector: { action: {} } }
    Power_6: { name: Power 6 clicks, default: [], selector: { action: {} } }

    Hue_1: { name: Hue 1 click, default: [], selector: { action: {} } }
    Hue_2: { name: Hue 2 clicks, default: [], selector: { action: {} } }
    Hue_3: { name: Hue 3 clicks, default: [], selector: { action: {} } }
    Hue_4: { name: Hue 4 clicks, default: [], selector: { action: {} } }
    Hue_5: { name: Hue 5 clicks, default: [], selector: { action: {} } }
    Hue_6: { name: Hue 6 clicks, default: [], selector: { action: {} } }

    Up_Hold: { name: Up Hold, default: [], selector: { action: {} } }
    Up_Release: { name: Up Release, default: [], selector: { action: {} } }
    Down_Hold: { name: Down Hold, default: [], selector: { action: {} } }
    Down_Release: { name: Down Release, default: [], selector: { action: {} } }

mode: restart
max_exceeded: silent

variables:
  target_device: !input zha_device
  window: !input click_window

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id == target_device }}

action:

  - variables:
      cmd: "{{ trigger.event.data.command }}"
      cluster: "{{ trigger.event.data.cluster_id | int }}"
      args: "{{ trigger.event.data.args | default([]) }}"
      direction: >
        {% if args|length > 0 and args[0] is number and args[0] > 0 %}
          up
        {% else %}
          down
        {% endif %}

  - choose:

      #################################################
      # POWER (cluster 6 + on)
      #################################################

      - conditions:
          - condition: template
            value_template: "{{ cluster == 6 and cmd == 'on' }}"
        sequence:

          - variables:
              clicks: 1

          - repeat:
              count: 5
              sequence:
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                  timeout:
                    milliseconds: !input click_window
                  continue_on_timeout: true

                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ wait.trigger is not none
                               and wait.trigger.event.data.device_id == target_device
                               and wait.trigger.event.data.cluster_id == 6
                               and wait.trigger.event.data.command == 'on' }}
                      sequence:
                        - variables:
                            clicks: "{{ clicks + 1 }}"
                    - default:
                        - stop: "Done counting"

          - choose:
              - conditions: [{ condition: template, value_template: "{{ clicks == 1 }}" }]
                sequence: !input Power_1
              - conditions: [{ condition: template, value_template: "{{ clicks == 2 }}" }]
                sequence: !input Power_2
              - conditions: [{ condition: template, value_template: "{{ clicks == 3 }}" }]
                sequence: !input Power_3
              - conditions: [{ condition: template, value_template: "{{ clicks == 4 }}" }]
                sequence: !input Power_4
              - conditions: [{ condition: template, value_template: "{{ clicks == 5 }}" }]
                sequence: !input Power_5
              - conditions: [{ condition: template, value_template: "{{ clicks >= 6 }}" }]
                sequence: !input Power_6

      #################################################
      # HUE (cluster 6 + off)
      #################################################

      - conditions:
          - condition: template
            value_template: "{{ cluster == 6 and cmd == 'off' }}"
        sequence:

          - variables:
              clicks: 1

          - repeat:
              count: 5
              sequence:
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                  timeout:
                    milliseconds: !input click_window
                  continue_on_timeout: true

                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ wait.trigger is not none
                               and wait.trigger.event.data.device_id == target_device
                               and wait.trigger.event.data.cluster_id == 6
                               and wait.trigger.event.data.command == 'off' }}
                      sequence:
                        - variables:
                            clicks: "{{ clicks + 1 }}"
                    - default:
                        - stop: "Done counting"

          - choose:
              - conditions: [{ condition: template, value_template: "{{ clicks == 1 }}" }]
                sequence: !input Hue_1
              - conditions: [{ condition: template, value_template: "{{ clicks == 2 }}" }]
                sequence: !input Hue_2
              - conditions: [{ condition: template, value_template: "{{ clicks == 3 }}" }]
                sequence: !input Hue_3
              - conditions: [{ condition: template, value_template: "{{ clicks == 4 }}" }]
                sequence: !input Hue_4
              - conditions: [{ condition: template, value_template: "{{ clicks == 5 }}" }]
                sequence: !input Hue_5
              - conditions: [{ condition: template, value_template: "{{ clicks >= 6 }}" }]
                sequence: !input Hue_6

      #################################################
      # HOLD + RELEASE (cluster 8)
      #################################################

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'move' and direction == 'up' }}"
        sequence: !input Up_Hold

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd == 'move' and direction == 'down' }}"
        sequence: !input Down_Hold

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd in ['stop','stop_with_on_off'] and direction == 'up' }}"
        sequence: !input Up_Release

      - conditions:
          - condition: template
            value_template: "{{ cluster == 8 and cmd in ['stop','stop_with_on_off'] and direction == 'down' }}"
        sequence: !input Down_Release
